name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: pip install --upgrade --pre hatch

    - if: matrix.python-version == '3.9' && runner.os == 'Linux'
      name: Lint
      run: hatch run lint:all

    - name: Run tests
      run: hatch run cov

    - if: matrix.python-version == '3.9'
      name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - if: matrix.python-version == '3.9'
      name: Run tests on Python 2.7
      run: hatch run test.py27:no-cov
